/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cop4331.shoppingCart;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTextArea;

/**
 * Buyer Main Panel
 *
 * @author Gregory Prosper
 */
public class BuyerMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form BuyerMainPanel
     */
    public BuyerMainPanel() {
        initComponents();
    }

    /**
     * Returns JList of items.
     *
     * @return JList of items.
     */
    public JList getItemList() {
        return itemList;
    }

    /**
     * Returns Item Details Text Area.
     *
     * @return Item Details Text Area.
     */
    public JTextArea getItemDetailsTextArea() {
        return itemDetailsTextArea;
    }

    /**
     * Checks to see if item is selected.
     *
     * @return true is item is selected.
     */
    public boolean itemSelected() {
        return !this.itemList.isSelectionEmpty();
    }

    /**
     * Returns Add to Cart Button.
     *
     * @return Add to Cart Button.
     */
    public JButton getAddToCartButton() {
        return addToCartButton;
    }

    /**
     * Returns Cart Button.
     *
     * @return Cart Button.
     */
    public JButton getCartButton() {
        return cartButton;
    }

    /**
     * Returns Logout Button.
     *
     * @return Logout Button.
     */
    public JButton getLogutButton() {
        return logutButton;
    }

    /**
     * Returns selected item from JList on SellerMainPanel.
     *
     * @return InventoryItem.
     */
    public InventoryItem getSelectedItem() {
        ArrayList<InventoryItem> item = (ArrayList<InventoryItem>) this.itemList.getSelectedValuesList();
        InventoryItem chosenItem = item.get(0);
        return chosenItem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addToCartButton = new javax.swing.JButton();
        cartButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemDetailsTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logutButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        addToCartButton.setText("Add to Cart");

        cartButton.setText("Cart");

        itemList.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        itemList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(itemList);

        itemDetailsTextArea.setEditable(false);
        itemDetailsTextArea.setColumns(15);
        itemDetailsTextArea.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        itemDetailsTextArea.setLineWrap(true);
        itemDetailsTextArea.setRows(5);
        itemDetailsTextArea.setWrapStyleWord(true);
        itemDetailsTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Item Details"));
        jScrollPane2.setViewportView(itemDetailsTextArea);

        jLabel1.setText("Item Name");

        jLabel2.setText("Price");

        logutButton.setText("Logout");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cop4331/shoppingCart/shoppingCart.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cartButton)
                                    .addComponent(addToCartButton)
                                    .addComponent(logutButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(288, 288, 288)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addToCartButton, cartButton, logutButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addToCartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cartButton)
                        .addGap(12, 12, 12)
                        .addComponent(logutButton)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Updates the item details Text Area with the selected item.
     */
    private void itemListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemListMouseClicked
        // TODO add your handling code here:
        InventoryItem chosenItem = this.getSelectedItem();
        this.itemDetailsTextArea.setText(String.format("%s\n\n$%.2f\n\nIn stock: %d\n\n%s", 
                chosenItem.getName(), chosenItem.getSalesPrice(),InventoryItem.amountInStock.get(chosenItem.getName()), chosenItem.getDescription()));
        this.itemDetailsTextArea.setCaretPosition(0);
    }//GEN-LAST:event_itemListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartButton;
    private javax.swing.JButton cartButton;
    private javax.swing.JTextArea itemDetailsTextArea;
    private javax.swing.JList itemList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logutButton;
    // End of variables declaration//GEN-END:variables
}
