/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cop4331.shoppingCart;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;

/**
 * Seller Main Panel
 *
 * @author Gregory Prosper
 */
public class SellerMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form SellerMainPanel
     */
    public SellerMainPanel() {
        initComponents();
    }

    /**
     * Returns RevenueLabel.
     *
     * @return RevenueLabel.
     */
    public JLabel getRevenueLabel() {
        return revenueLabel;
    }

    /**
     * Returns CostLabel.
     *
     * @return CostLabel.
     */
    public JLabel getCostLabel() {
        return costLabel;
    }

    /**
     * Returns ProfitLabel.
     *
     * @return ProfitLabel.
     */
    public JLabel getProfitLabel() {
        return profitLabel;
    }

    /**
     * Returns ResetButton.
     *
     * @return ResetButton.
     */
    public JButton getResetButton() {
        return resetButton;
    }

    /**
     * Returns inventory JList of SellerMainPanel.
     *
     * @return JList of SellerMainPanel.
     */
    public JList getInventoryList() {
        return inventoryList;
    }

    /**
     * Returns logout button.
     *
     * @return Logout button.
     */
    public JButton getLogoutButton() {
        return logoutButton;
    }

    /**
     * Returns Modify Item Button.
     *
     * @return Modify Item Button.
     */
    public JButton getModifyItemButton() {
        return modifyItemButton;
    }

    /**
     * Returns Add to Inventory Button.
     *
     * @return Add to Inventory Button.
     */
    public JButton getAddItemToInventory() {
        return addItemToInventory;
    }

    /**
     * Returns Remove From Inventory Button.
     *
     * @return Remove From Inventory Button.
     */
    public JButton getRemoveFromInventoryButton() {
        return removeFromInventoryButton;
    }

    /**
     * Returns selected item from JList on SellerMainPanel.
     *
     * @return UserItem.
     */
    public UserItem getSelectedItem() {
        ArrayList<UserItem> item = (ArrayList<UserItem>) this.inventoryList.getSelectedValuesList();
        UserItem chosenItem = item.get(0);
        return chosenItem;
    }

    /**
     * Checks to see if item is selected.
     *
     * @return true is item is selected.
     */
    public boolean itemSelected() {
        return !this.inventoryList.isSelectionEmpty();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modifyItemButton = new javax.swing.JButton();
        removeFromInventoryButton = new javax.swing.JButton();
        addItemToInventory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryList = new javax.swing.JList();
        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        revenueLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        profitLabel = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();

        modifyItemButton.setText("Modify Item");

        removeFromInventoryButton.setText("Remove from Inventory");

        addItemToInventory.setText("Add Item to Inventory");

        inventoryList.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(inventoryList);

        logoutButton.setText("Logout");

        jLabel1.setText("Item Name");

        jLabel2.setText("Invoice Price");

        jLabel3.setText("Sales Price");

        jLabel4.setText("Stock");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cop4331/shoppingCart/shoppingCart.png"))); // NOI18N

        jLabel6.setText("Revenue:");

        jLabel7.setText("Cost:");

        jLabel8.setText("Profit:");

        revenueLabel.setText("90000");

        costLabel.setText("45000");

        profitLabel.setText("45000");

        resetButton.setText("Reset Statistics");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(revenueLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(costLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(profitLabel)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modifyItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addItemToInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeFromInventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel6, jLabel7, jLabel8});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(revenueLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(costLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(profitLabel))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(modifyItemButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeFromInventoryButton)
                        .addGap(18, 18, 18)
                        .addComponent(addItemToInventory)
                        .addGap(18, 18, 18)
                        .addComponent(resetButton)
                        .addGap(18, 18, 18)
                        .addComponent(logoutButton)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemToInventory;
    private javax.swing.JLabel costLabel;
    private javax.swing.JList inventoryList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton modifyItemButton;
    private javax.swing.JLabel profitLabel;
    private javax.swing.JButton removeFromInventoryButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel revenueLabel;
    // End of variables declaration//GEN-END:variables
}
